var Stage01 = {
  "map": {
    "w": 10,
    "h": 200,
    "grid": 32,
    "chars": {
"d":"deck",
"e":"deck1",
"f":"cannonL",
"g":"cannonR",
"h":"way",
"i":"deck2",
"j":"grass",
"k":"coco",
"l":"way1",
"m":"way8",
"n":"way5",
"o":"way3",
"p":"way2",
"q":"bush_ws",
"r":"bush_en",
"A":"beach_s",
"s":"bush_dwn",
"B":"beach_e",
"t":"bush_e",
"C":"beach_ws",
"u":"bush_n",
"D":"beach_en",
"v":"bush",
"E":"bush_es",
"w":"bush_den",
"F":"beach_w",
"x":"bush_des",
"G":"beach_den",
"y":"bush_s",
"H":"beach_dwn",
"z":"beach_des",
"I":"beach_dws",
"J":"bush_w",
"K":"beach_es",
"L":"beach_n",
"M":"bush_wn",
"N":"bush_dws",
"O":"beach_wn",
"P":"way4",
"a":"sea",
"b":"deck4",
"c":"deck5",
"9":"deck3",
   },
    "matrix": [

"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaa9bcaaa",
"aaaadedaaa",
"aaafdedgaa",
"aaaadedaaa",
"aaafdedgaa",
"aaaadedaaa",
"aaafdedaaa",
"aaaadhdaaa",
"aaafdddgaa",
"aaaaiiiaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"hhhaaaahaa",
"aaaaaahhaa",
"aaaaaahhaa",
"hhhhhhhhhh",
"hhhhhhhhhh",
"hhhhhhhhhh",
"jjjjjhjjjj",
"kjkkjhjkkj",
"jjjjjhjjjj",
"jjjjjhjjkj",
"hhhhhhhhhh",
"jjjjjhjjjj",
"jjjjjhjjjj",
"jjjjjhjjjj",
"jkjkjhjjkk",
"jjjjjhjkjj",
"jjjjjhjjjj",
"jjjhhhhhhh",
"jjjhhhhhhh",
"jjjjjjjjjj",
"jjjjjjjjjj",
"jjjjjjjjjj",
"jjjjjjjjjl",
"jjjjjjjjlh",
"jjjjjjjlhh",
"jjjjjjlhhh",
"hhhhhhhhhh",
"hmhnnnnnnn",
"hhhhhhhhhh",
"jjlhhhojjj",
"jlhhhojjjj",
"jphhojjjjj",
"jjpojjjjjj",
"jjjjjjjjjj",
"jjjjjjjjjj",
"jjjjjjjjjj",
"jjjjjjjjjj",
"jjjjjjjjjj",
"jjjjjjjjjj",
"jjjjjjjjjj",
"jjjjjjqrjj",
"jjjjjqstjj",
"uuuuusvwuu",
"vvvvvvvvvv",
"vvvvvvvvvv",
"vvvvvvvvvv",
"vvvvvvvvvv",
"vvvvvvxyyy",
"vvvvvvtzAA",
"vvvvvvtBCD",
"vvvvvxEBFB",
"vvvxyEjGHG",
"vxyEjjjquu",
"xEjjjjqsvv",
"tzAAIqsvvv",
"tBCDFJvvvv",
"tBFBFJvvvv",
"EBFBFJvvvv",
"AKFBFJvvvv",
"LLHBFMNvvv",
"jjjBOIJvvv",
"jjjGDFJvvv",
"jjjjBFJvvv",
"jjjjBFJvvv",
"jjjjBFJvvv",
"jjjjBFJvvv",
"urjjBFJvvv",
"vtjjBFMNvv",
"vtjjBOIJvv",
"vwrjGDFJvv",
"vvwurBFJvv",
"vvvvtBFJvv",
"vvvvtBFJvv",
"vvvvtBFJvv",
"vvvvtBFMyy",
"vvvvtBFzAA",
"vvvvtBOKCL",
"vvvvtGLLHq",
"vvvvwuuuus",
"vvvvvvvvvv",
"vvvvvvvvvv",
"vvvvvvvvvv",
"vvvvvvvvvv",
"vvvvvvxyNv",
"vvvvvvwusv",
"vvvvvvvvvv",
"vvvvvvvvvv",
"vvvvvvvvvv",
"vvvvvvvvvv",
"yyyyyNvvvv",
"hhhPjMNvvv",
"uurpPjMNvv",
"vvwrpPjMNv",
"vvvwrhjjJv",
"vvvvthzIJv",
"vvvvthBFMy",
"vvvxEjBFzA",
"yyyEjzKOKa",
"jjjzAKaaaa",
"jzAKaaaaaa",
"zKaaaaaaaa",
"Kaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaCDaaaaaa",
"aaOKaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaC",
"aaaaaaaaCH",
"aaaaaCLLHj",
"aaaaCHjjjq",
"aCLLHzIjjJ",
"aFjjjGHjqs",
"aFkjjjjjJv",
"CHquuuuusv",
"Hqsvvvvvvv",
"qsvvvvvvvv",
"svxyyyyNvv",
"vvtjjjjJvv",
"yyEjjjjMyy",
"AAAAAAAAAA",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaCDaaaaaa",
"aaOKaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaCDaaa",
"aaaaCHBaaa",
"aaaCHzKaaa",
"aaaFzKaaaa",
"aaaOKaaaaa",
"aaaaaaaaaa",
"Daaaaaaaaa",
"Kaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaCDaa",
"aaaaaaOKaa",
"aaaaaaaaaa",
"aCLLDaaaaa",
"aOAAKaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
"aaaaaaaaaa",
    ]
  },
  "ground": [
{x:208, y:5456,  name:"cannon", opts:{type:"cannon"}},
{x:112, y:5456,  name:"cannon", opts:{type:"cannon"}},
{x:176, y:5456,  name:"arsenal", opts:{type:"base2"}},
{x:144, y:5456,  name:"arsenal", opts:{type:"base3"}},
{x:112, y:5296,  name:"lodge", opts:{type:"base"}},
{x:176, y:4624,  name:"arsenal", opts:{type:"base"}},
{x:144, y:4656,  name:"cannon", opts:{type:"cannon"}},
{x:16, y:4432,  name:"cannon", opts:{type:"cannon2"}},
{x:48, y:4432,  name:"cannon", opts:{type:"cannon"}},
{x:157, y:4449,  name:"cannon", opts:{type:"cannon2"}},
{x:179, y:4473,  name:"cannon", opts:{type:"cannon2"}},
{x:208, y:4528,  name:"arsenal", opts:{type:"base"}},
{x:240, y:4528,  name:"arsenal", opts:{type:"base2"}},
{x:95, y:4928,  name:"cannon", opts:{type:"cannon3"}},
{x:226, y:4224,  name:"cannon", opts:{type:"cannon2"}},
{x:252, y:4225,  name:"cannon", opts:{type:"cannon2"}},
{x:16, y:3600,  name:"cannon", opts:{type:"cannon2"}},
{x:48, y:3600,  name:"cannon", opts:{type:"cannon3"}},
{x:16, y:3568,  name:"arsenal", opts:{type:"base2"}},
{x:48, y:3568,  name:"arsenal", opts:{type:"base"}},
{x:16, y:3504,  name:"lodge", opts:{type:"base"}},
{x:48, y:3504,  name:"lodge", opts:{type:"base"}},
{x:48, y:3536,  name:"lodge", opts:{type:"base"}},
{x:16, y:3536,  name:"lodge", opts:{type:"base"}},
{x:112, y:3248,  name:"arsenal", opts:{type:"base3"}},
{x:80, y:3248,  name:"arsenal", opts:{type:"base"}},
{x:176, y:3216,  name:"cannon", opts:{type:"cannon2"}},
{x:144, y:3216,  name:"cannon", opts:{type:"cannon3"}},
{x:208, y:3184,  name:"cannon", opts:{type:"cannon"}},
{x:112, y:2608,  name:"cannon", opts:{type:"cannon2"}},
{x:240, y:2480,  name:"cannon", opts:{type:"cannon2"}},
{x:16, y:2480,  name:"cannon", opts:{type:"cannon2"}},
{x:176, y:2352,  name:"cannon", opts:{type:"cannon2"}},
{x:16, y:2352,  name:"cannon", opts:{type:"cannon2"}},
{x:112, y:2128,  name:"arsenal", opts:{type:"base2"}},
{x:144, y:2128,  name:"arsenal", opts:{type:null}},
{x:176, y:2128,  name:"arsenal", opts:{type:null}},
{x:240, y:2128,  name:"arsenal", opts:{type:null}},
{x:208, y:2128,  name:"arsenal", opts:{type:null}},
{x:304, y:2128,  name:"arsenal", opts:{type:"base3"}},
{x:272, y:2128,  name:"arsenal", opts:{type:null}},
{x:80, y:2128,  name:"cannon", opts:{type:"cannon2"}},
{x:112, y:2160,  name:"cannon", opts:{type:"cannon3"}},
{x:48, y:1808,  name:"lodge", opts:{type:"base"}},
{x:80, y:1840,  name:"lodge", opts:{type:"base"}},
{x:48, y:1840,  name:"lodge", opts:{type:"base"}},
{x:16, y:1808,  name:"lodge", opts:{type:"base"}},
{x:16, y:1840,  name:"lodge", opts:{type:"base"}},
{x:144, y:1808,  name:"lodge", opts:{type:"base"}},
{x:144, y:1840,  name:"lodge", opts:{type:"base"}},
{x:112, y:1840,  name:"lodge", opts:{type:"base"}},
{x:112, y:1808,  name:"lodge", opts:{type:"base"}},
{x:16, y:1904,  name:"lodge", opts:{type:null}},
{x:48, y:1904,  name:"lodge", opts:{type:null}},
{x:112, y:1904,  name:"lodge", opts:{type:null}},
{x:144, y:1904,  name:"lodge", opts:{type:null}},
{x:112, y:1968,  name:"lodge", opts:{type:null}},
{x:144, y:1936,  name:"lodge", opts:{type:null}},
{x:144, y:1968,  name:"lodge", opts:{type:null}},
{x:80, y:1904,  name:"lodge", opts:{type:null}},
{x:80, y:1936,  name:"lodge", opts:{type:null}},
{x:48, y:1936,  name:"lodge", opts:{type:null}},
{x:16, y:1968,  name:"lodge", opts:{type:null}},
{x:240, y:1904,  name:"lodge", opts:{type:null}},
{x:208, y:1936,  name:"lodge", opts:{type:null}},
{x:208, y:1968,  name:"lodge", opts:{type:null}},
{x:208, y:1904,  name:"lodge", opts:{type:null}},
{x:240, y:1936,  name:"lodge", opts:{type:null}},
{x:304, y:1904,  name:"lodge", opts:{type:null}},
{x:272, y:1904,  name:"lodge", opts:{type:null}},
{x:208, y:1840,  name:"lodge", opts:{type:"base"}},
{x:208, y:1808,  name:"lodge", opts:{type:"base"}},
{x:240, y:1840,  name:"lodge", opts:{type:"base"}},
{x:272, y:1808,  name:"lodge", opts:{type:"base"}},
{x:304, y:1840,  name:"lodge", opts:{type:"base"}},
{x:16, y:1648,  name:"arsenal", opts:{type:"base"}},
{x:48, y:1648,  name:"arsenal", opts:{type:"base"}},
{x:80, y:1648,  name:"arsenal", opts:{type:"base"}},
{x:144, y:1648,  name:"arsenal", opts:{type:"base3"}},
{x:112, y:1648,  name:"arsenal", opts:{type:"base"}},
{x:176, y:1648,  name:"arsenal", opts:{type:"base3"}},
{x:272, y:1648,  name:"arsenal", opts:{type:"base2"}},
{x:304, y:1648,  name:"arsenal", opts:{type:"base"}},
{x:48, y:1712,  name:"cannon", opts:{type:"cannon2"}},
{x:16, y:1712,  name:"cannon", opts:{type:"cannon2"}},
{x:272, y:1712,  name:"cannon", opts:{type:"cannon2"}},
{x:304, y:1712,  name:"cannon", opts:{type:"cannon2"}},
{x:240, y:1552,  name:"cannon", opts:{type:"cannon3"}},
{x:208, y:1584,  name:"cannon", opts:{type:"cannon"}},
{x:80, y:1552,  name:"cannon", opts:{type:"cannon"}},
{x:118, y:753,  name:"cannon", opts:{type:"cannon2"}},
{x:118, y:817,  name:"cannon", opts:{type:"cannon3"}},
{x:233, y:817,  name:"cannon", opts:{type:"cannon3"}},
{x:233, y:690,  name:"cannon", opts:{type:"cannon2"}},
{x:234, y:625,  name:"cannon", opts:{type:"cannon"}},
{x:119, y:689,  name:"cannon", opts:{type:"cannon2"}},
{x:118, y:625,  name:"cannon", opts:{type:"cannon"}},
{x:80, y:2096,  name:"cannon", opts:{type:"cannon"}},
{x:192, y:6000,  name:"cannon", opts:{type:"cannon"}},
  ],
  "air": [
{x:112, y:5584,  name:"f4f", opts:{type:"stalk"}},
{x:176, y:5584,  name:"f4f", opts:{type:"stalk"}},
{x:144, y:5616,  name:"f4f", opts:{type:"stalk"}},
{x:144, y:5552,  name:"f4f", opts:{type:"stalk"}},
{x:48, y:5360,  name:"p38", opts:{type:"dive"}},
{x:176, y:5360,  name:"p38", opts:{type:"dive"}},
{x:112, y:5392,  name:"p38", opts:{type:"dive"}},
{x:240, y:5328,  name:"p38", opts:{type:"dive"}},
{x:48, y:5744,  name:"f4f", opts:{type:"furafura1"}},
{x:144, y:5712,  name:"f4f", opts:{type:"furafura1"}},
{x:208, y:5744,  name:"f4f", opts:{type:"stalk"}},
{x:272, y:5712,  name:"f4f", opts:{type:"furafura1"}},
{x:48, y:5072,  name:"f4f", opts:{type:"stalk"}},
{x:16, y:5040,  name:"f4f", opts:{type:"stalk"}},
{x:272, y:5040,  name:"f4f", opts:{type:"stalk"}},
{x:304, y:5008,  name:"f4f", opts:{type:"stalk"}},
{x:48, y:4592,  name:"p38", opts:{type:"dive"}},
{x:97, y:4595,  name:"p38", opts:{type:"dive"}},
{x:144, y:4592,  name:"p38", opts:{type:"dive"}},
{x:192, y:4588,  name:"p38", opts:{type:"dive"}},
{x:134, y:4469,  name:"f4f", opts:{type:"stalk"}},
{x:165, y:4475,  name:"f4f", opts:{type:"stalk"}},
{x:200, y:4468,  name:"f4f", opts:{type:"stalk"}},
{x:232, y:4459,  name:"f4f", opts:{type:"stalk"}},
{x:112, y:4144,  name:"f4f", opts:{type:"furafura1"}},
{x:176, y:4144,  name:"f4f", opts:{type:"furafura1"}},
{x:240, y:4144,  name:"f4f", opts:{type:"furafura1"}},
{x:48, y:4144,  name:"f4f", opts:{type:"furafura1"}},
{x:80, y:3888,  name:"f4f", opts:{type:"stalk"}},
{x:112, y:3920,  name:"f4f", opts:{type:"furafura1"}},
{x:112, y:3856,  name:"f4f", opts:{type:"stalk"}},
{x:144, y:3888,  name:"f4f", opts:{type:"dive"}},
{x:240, y:3504,  name:"f4f", opts:{type:"stalk"}},
{x:272, y:3536,  name:"f4f", opts:{type:"stalk"}},
{x:80, y:3056,  name:"p38", opts:{type:"furafura1"}},
{x:144, y:3056,  name:"p38", opts:{type:"stalk"}},
{x:208, y:3056,  name:"p38", opts:{type:"furafura1"}},
{x:272, y:3056,  name:"p38", opts:{type:"stalk"}},
{x:144, y:2608,  name:"f4f", opts:{type:"furafura1"}},
{x:112, y:2640,  name:"f4f", opts:{type:"stalk"}},
{x:144, y:2672,  name:"f4f", opts:{type:"stalk"}},
{x:176, y:2640,  name:"f4f", opts:{type:"furafura1"}},
{x:112, y:2256,  name:"f4f", opts:{type:"furafura1"}},
{x:240, y:2256,  name:"f4f", opts:{type:"furafura1"}},
{x:48, y:2224,  name:"p38", opts:{type:"stalk"}},
{x:176, y:2224,  name:"p38", opts:{type:"stalk"}},
{x:112, y:2000,  name:"p38", opts:{type:"dive"}},
{x:176, y:2000,  name:"p38", opts:{type:"dive"}},
{x:176, y:1968,  name:"p38", opts:{type:"dive"}},
{x:112, y:1968,  name:"p38", opts:{type:"dive"}},
{x:48, y:1872,  name:"f4f", opts:{type:"stalk"}},
{x:272, y:1872,  name:"f4f", opts:{type:"stalk"}},
{x:301, y:1863,  name:"f4f", opts:{type:"stalk"}},
{x:16, y:1863,  name:"f4f", opts:{type:"stalk"}},
{x:16, y:1264,  name:"f4f", opts:{type:"stalk"}},
{x:304, y:1232,  name:"f4f", opts:{type:"stalk"}},
{x:16, y:1072,  name:"f4f", opts:{type:"stalk"}},
{x:304, y:1040,  name:"f4f", opts:{type:"stalk"}},
{x:304, y:400,  name:"f4f", opts:{type:"stalk"}},
{x:16, y:400,  name:"f4f", opts:{type:"stalk"}},
{x:51, y:387,  name:"f4f", opts:{type:"stalk"}},
{x:276, y:388,  name:"f4f", opts:{type:"stalk"}},
{x:147, y:354,  name:"f4f", opts:{type:"furafura1"}},
{x:195, y:352,  name:"f4f", opts:{type:"furafura1"}},
{x:80, y:304,  name:"f4f", opts:{type:"furafura1"}},
{x:240, y:304,  name:"f4f", opts:{type:"furafura1"}},
{x:112, y:240,  name:"p38", opts:{type:"dive"}},
{x:208, y:240,  name:"p38", opts:{type:"dive"}},
{x:110, y:215,  name:"p38", opts:{type:"dive"}},
{x:206, y:215,  name:"p38", opts:{type:"dive"}},
{x:48, y:144,  name:"f4f", opts:{type:"stalk"}},
{x:272, y:112,  name:"f4f", opts:{type:"stalk"}},
{x:80, y:112,  name:"f4f", opts:{type:"stalk"}},
{x:240, y:80,  name:"f4f", opts:{type:"stalk"}},
{x:112, y:80,  name:"f4f", opts:{type:"stalk"}},
{x:208, y:48,  name:"f4f", opts:{type:"stalk"}},
{x:144, y:48,  name:"f4f", opts:{type:"stalk"}},
{x:176, y:16,  name:"f4f", opts:{type:"stalk"}},
{x:208, y:752,  name:"bridge", opts:{type:"boss"}},
//{x:192, y:6000,  name:"bridge", opts:{type:"boss"}},
  ]
};

(function(Stage) {
	var chars = Stage.map.chars;
	for (var ch in chars) {
		var name = chars[ch];
		Chip.add(name, "img/map/"+name+".png");
	}

	Stage.createActors = function(game) {
		var grounds = Stage.ground;
		for ( var i = 0; i < grounds.length; i++) {
			var entity = createGround(game, grounds[i]);
			game.addEntity(entity);
		}

		var airs = Stage.air;
		for ( var i = 0; i < airs.length; i++) {
			var entity = createAir(game, airs[i]);
			game.addEntity(entity);
		}
	}
	
	function createGround(game, data) {
		var ent;
		if (data.name == "lodge")   ent = new Lodge(game);
		if (data.name == "arsenal") ent = new Arsenal(game);
		if (data.name == "cannon")  ent = new Cannon(game);
		if (ent[data.opts.type]) {
			ent.action = ent[data.opts.type];
		}

		ent.x = data.x;
		ent.y = data.y;
		return ent;
	}

	function createAir(game, data) {
		var ent;
		if (data.name == "f4f") ent = new F4f(game);
		if (data.name == "p38") ent = new P38(game);
		if (data.name == "bridge") ent = new Bridge(game);

		if (ent[data.opts.type]) {
			ent.action = ent[data.opts.type];
		}

		ent.x = data.x;
		ent.y = data.y;
		return ent;
	}

})(Stage01);














